### ISSUE TITLE
iOS Discovery URL return 404

### ISSUE THREAD

**Issue by palanivelus** [wjayesh/prod_app#1]
Hi,

It's working fine on  android, but not working in iOS, the problem is discovered URL return 404 in iOS.

Regards,
Palani

**Comment by wjayesh** [comment]
Hi, I feel this should work fine on iOS too since this is not an OS-specific feature. 
Can you expand on the problem a bit? As far as I understand your comment, there's an issue with the discovery URL?

**Comment by palanivelus** [comment]
I tried  to run app on iOS with your AD configuration but getting the discovery URL error. Attached screen shot for your reference. Please make sure it's working fine in android device.
![image](https://user-images.githubusercontent.com/6434945/83952073-d0f9b880-a853-11ea-8cca-508b94c116cb.png)

**Comment by wjayesh** [comment]
This is happening because I haven't registered an iOS client in my Azure portal. Keep in mind that before using a client, you have to register that in the portal and also put some settings into the code of your app so that the connection can be established.

**Comment by wjayesh** [comment]
From my [article](https://medium.com/flutter-community/flutter-azure-authentication-with-ad-b2c-8b76c81dd48e), 

>The client id helps Azure know that the application requesting authentication is indeed yours. To allow that, you have to first register your app in the tenant. This link has the steps required for the same.
You’ll notice that a “redirect URL” is required to complete the registration. This URL specifies the address to which the tokens and related information should be sent back from the authentication window.
>Since we’re building a native application, we will want the user redirected to the app after authentication. For this we can register a custom URL scheme that’ll launch our app. This is done in build.gradle(app) under the Android folder."
